# Generated by Django 3.2.13 on 2022-06-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
